
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/fastapi
    environment:
      - ELASTIC_CLOUD_ID=${ELASTIC_CLOUD_ID}
      - ELASTIC_CLOUD_AUTH=${ELASTIC_CLOUD_AUTH}

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.1
    volumes:
      - "./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
    environment:
      - ELASTIC_CLOUD_ENDPOINT=${ELASTIC_CLOUD_ENDPOINT}
      - ELASTIC_CLOUD_ID=${ELASTIC_CLOUD_ID}
      - ELASTIC_CLOUD_AUTH=${ELASTIC_CLOUD_AUTH}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5044:5044"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.14.1
    volumes:
      - "./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    environment:
      - ELASTIC_CLOUD_ENDPOINT=${ELASTIC_CLOUD_ENDPOINT}
      - ELASTIC_CLOUD_ID=${ELASTIC_CLOUD_ID}
      - ELASTIC_CLOUD_AUTH=${ELASTIC_CLOUD_AUTH}
    user: root