- module: system
  period: 60s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - uptime

- module: docker
  period: 60s
  hosts: ["unix:///var/run/docker.sock"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~